# -------------------------------------------------------------------------------
# Generated by PixieDust code generator
# 
# Licensed under the Apache License, Version 2.0 (the 'License');
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an 'AS IS' BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# Inherited from maven-artifact https://github.com/hamnis/maven-artifact
# -------------------------------------------------------------------------------

from pixiedust.display.chart.renderers import PixiedustRenderer
from pixiedust.display.chart.renderers.baseChartDisplay import BaseChartDisplay,commonChartOptions
from pixiedust.utils import Logger
from six import with_metaclass
from abc import ABCMeta

@PixiedustRenderer(rendererId="bCharts")
@Logger()
class BChartsBaseDisplay(with_metaclass(ABCMeta, BaseChartDisplay)):
	pass
	
	"""
	The code below adds dynamic chart options for your renderer.
	Note: the @commonChartOptions decorator will inject these options to every renderer class that inherit from this class
	Subclass can then use self.options.get("coolOption", None) to test user preferences
	"""
	@commonChartOptions
	def getChartOptions(self):
		return [

			{
                'name': 'showDesigner',
                'description': "Show Chart Designer?",
                'metadata': {
                    'type': "dropdown",
                    'values': ["Yes", "No"],
                    'default': "No"
                }
            },
            {
                'name': 'chartsize',
                'description': 'Chart Size',
                'metadata': {
                    'type': 'slider',
                    'max': 100,
                    'min': 50,
                    'default': 100
                }
            },
            {
                'name': 'chartURL',
                'description': 'Show Chart URL',
                'metadata': {
                    'type': 'checkbox',
                    'default': "true"
                }
            }

		]

    